Added flow for installing system paths and user config via main Makefile using sudo make install. Creates a user-specific header in common/config to define where cache and such is stored.

diff --git a/native/Makefile b/native/Makefile
--- a/native/Makefile
+++ b/native/Makefile
@@ -1,18 +1,31 @@
 # avanza-2-native Makefile
 
-PROJECT_NAME := avanza-2-native
+PROJECT_NAME   := avanza-2-native
+
+# Define dir paths that should be created with make install
+LOG_DIR 			 			:= /var/log/avanza2/
+DATA_DIR      			:= /var/lib/avanza2/
+DATA_CACHE_DIR      := /var/lib/avanza2/cache/
+DATA_CACHE_RATE_DIR := /var/lib/avanza2/cache/rate/
+
+# Header where paths are stored
+USER_CONFIG_H  := common/config/include/user_config.h
+
+# User to install for
+UID ?= 1000
+GID ?= 1000
 
 # Modules to build. Update this list if you add subdirectories.
-MODULES := jna_poc risk
+MODULES 			 := jna_poc risk
 
 # Include paths for root-level headers
-export CFLAGS += -I./include
+export CFLAGS  += -I./include
 
 #############################
 # PHONIES
 #############################
 
-.PHONY: all clean deps \
+.PHONY: all clean deps install \
 	$(MODULES) \
 	$(addsuffix /install,$(MODULES)) \
 	$(addsuffix /run,$(MODULES)) \
@@ -27,6 +40,28 @@ export CFLAGS += -I./include
 #############################
 # Recipes
 #############################
+
+# Install runtime environment
+install:
+	@if [ "$$(id -u)" -ne 0 ]; then \
+		echo "Root privileges required, please run with sudo."; \
+		exit 1; \
+	fi
+
+	@echo "Creating directories with necessary permissions..."
+	install -o $(UID) -g $(GID) -d -m 0755 $(LOG_DIR)
+	install -o $(UID) -g $(GID) -d -m 0755 $(DATA_DIR)
+	install -o $(UID) -g $(GID) -d -m 0755 $(DATA_CACHE_DIR)
+	install -o $(UID) -g $(GID) -d -m 0755 $(DATA_CACHE_RATE_DIR)
+
+	@echo "Generating new $(USER_CONFIG_H)..."
+	@echo "#ifndef __USER_CONFIG_H__" 			 	   									 >  $(USER_CONFIG_H)
+	@echo "#define __USER_CONFIG_H__" 			 	   									 >> $(USER_CONFIG_H)
+	@echo "#define LOG_DIR \"$(LOG_DIR)\"" 									       >> $(USER_CONFIG_H)
+	@echo "#define DATA_DIR \"$(DATA_DIR)\"" 	   									 >> $(USER_CONFIG_H)
+	@echo "#define DATA_CACHE_DIR \"$(DATA_CACHE_DIR)\"" 	         >> $(USER_CONFIG_H)
+	@echo "#define DATA_CACHE_RATE_DIR \"$(DATA_CACHE_RATE_DIR)\"" >> $(USER_CONFIG_H)
+	@echo "#endif" 															 									 >> $(USER_CONFIG_H)
 
 # Default target: build all modules
 all: $(MODULES)
